{{- if .Values.secrets.default.enabled }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secrets.secretName }}
data:
  # retrieve the secret data using lookup function and when not exists, return an empty dictionary / map as result
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.secrets.secretName) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  # set $secret to existing secret data or generate a random one when not exists
  {{- $secret := (get $secretData .Values.secrets.secretKey) | default (randAlphaNum 32 | b64enc) }}
  {{ .Values.secrets.secretKey }}: {{ $secret | quote }}
{{- end }}