name: Push code to S3

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  push-dags-lib-to-s3:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Publish to S3
      run: aws s3 cp --recursive ./airflow/dags  s3://${{ secrets.BUCKET_NAME }}/${{ secrets.DAGS_FOLDER }} --exclude "*.pyc"

  build-image-and-push:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t nalexx6-practice:latest .

      - name: Tag Docker Image
        run: |
          docker tag nalexx6-practice:latest ${{ secrets.DOCKER_USERNAME }}/nalexx6-practice:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nalexx6-practice:latest